### ISSUE TITLE
To use essential matrix solver LAPACK or Eigen has to be installed!

### ISSUE THREAD

**Issue by youwei2567** [Easonyesheng/A2PM-MESA#3]
Sorry to bother again!
When  the test code was running to geo_area_match process, it encountered LAPACK or Eigen missing problem in  cv2.findEssentialMat in geo.py line 668.
I subimit this issue to make sure if it is necessary to install LAPACK or Eigen in your environment. Could you please check this installation.

Here is traceback:
`
Traceback (most recent call last):
  File "test_a2pm.py", line 151, in <module>
    test()
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/youwei/.conda/envs/yw_torch/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "test_a2pm.py", line 109, in test
    alpha_corrs_dict, alpha_inlier_idxs_dict, _ = gamer.geo_area_matching_refine(area_matches0, area_matches1)
  File "../geo_area_matchers/egam.py", line 247, in geo_area_matching_refine
    alpha_corrs_dict, alpha_inlier_idxs_dict = self.geo_area_match_rejection(matched_areas0, matched_areas1)
  File "../geo_area_matchers/egam.py", line 466, in geo_area_match_rejection
    temp_inlier_corrs, temp_F, temp_self_sampson_dist = self.inside_area_match_calculation(area0, area1, idx)
  File "../geo_area_matchers/egam.py", line 658, in inside_area_match_calculation
    E, inlier_corrs = calc_E_from_corrs(temp_corrs, self.K0, self.K1, sac_mode=self.sac_mode)
  File "../utils/geo.py", line 668, in calc_E_from_corrs
    E, mask = cv2.findEssentialMat(
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/calib3d/src/usac/essential_solver.cpp:197: error: (-213:The function/feature is not implemented) To use essential matrix solver LAPACK or Eigen has to be installed! in function 'estimate'
`

**Comment by Easonyesheng** [comment]
Hi @youwei2567 
It seems like an issue of opencv-python, see [here](https://github.com/opencv/opencv-python/issues/534).
I think you can update the version of opencv-python (like 4.5.1 -> 4.8.0) and I checked my opencv version is 4.8.0, which works well.

**Comment by Easonyesheng** [comment]
Thanks for your reminder.
I have fixed it.

**Comment by youwei2567** [comment]
After updating, it goes well!
Thx!
