### ISSUE TITLE
why i can't run the Benchmark Test?Can Bash run the test ?

### ISSUE THREAD

**Issue by MY-QY** [Easonyesheng/A2PM-MESA#9]
$ bash mesa-f-dkm-sn.sh
scene_name = scene0720_00
pair0 = 0
pair1 = 2520
LexerNoViableAltException: dataset.image_name1=2520
                                                   ^
Traceback (most recent call last):
  File "F:\VSCodeProject\A2PM-MESA\scripts\test_a2pm.py", line 17, in <module>
    from loguru import logger
  File "F:\LittlePrograms\Python311\Lib\site-packages\loguru\__init__.py", line 31, in <module>
    logger.add(_sys.stderr)
  File "F:\LittlePrograms\Python311\Lib\site-packages\loguru\_logger.py", line 804, in add
    colorize = _colorama.should_colorize(sink)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\LittlePrograms\Python311\Lib\site-packages\loguru\_colorama.py", line 11, in should_colorize
    import ipykernel
  File "C:\Users\32120\AppData\Roaming\Python\Python311\site-packages\ipykernel\__init__.py", line 7, in <module>
    from .connect import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\32120\AppData\Roaming\Python\Python311\site-packages\ipykernel\connect.py", line 12, in <module>
    import jupyter_client
  File "C:\Users\32120\AppData\Roaming\Python\Python311\site-packages\jupyter_client\__init__.py", line 3, in <module>
    from .asynchronous import AsyncKernelClient
  File "C:\Users\32120\AppData\Roaming\Python\Python311\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\32120\AppData\Roaming\Python\Python311\site-packages\jupyter_client\asynchronous\client.py", line 11, in <module>
    from ..channels import AsyncZMQSocketChannel, HBChannel
  File "C:\Users\32120\AppData\Roaming\Python\Python311\site-packages\jupyter_client\channels.py", line 16, in <module>
    from .session import Session
  File "C:\Users\32120\AppData\Roaming\Python\Python311\site-packages\jupyter_client\session.py", line 53, in <module>
    from .jsonutil import extract_dates, json_clean, json_default, squash_dates
  File "C:\Users\32120\AppData\Roaming\Python\Python311\site-packages\jupyter_client\jsonutil.py", line 14, in <module>
    from dateutil.parser import parse as _dateutil_parse
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1138, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1078, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1640, in find_spec
  File "<frozen importlib._bootstrap_external>", line 105, in _path_join

**Comment by MY-QY** [comment]
I run the project on Windows,running  the test needs any preparation?

**Comment by Easonyesheng** [comment]
I have not tested this code on Windows.
But according to the error info, `LexerNoViableAltException: dataset.image_name1=2520`, I think you can try to modify the shell script to make the python command in a single line? Not very sure.
By the way, before running the script, you need to modify the data path in dataloader's `yaml` file.
In your case, the `root_path` and `sem_folder` in `/conf/dataset/scannet_sam.yaml` need to be fixed to your path of scannet data and SAM segmentation results.

**Comment by MY-QY** [comment]
谢谢学长，课程大作业全靠学长了，上次答应的windows运行建议因为考研和毕设忙的都忘了，非常抱歉！附上能够运行demo.py的修改


&nbsp;


FREE.ICE
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eason ***@***.***&gt;; 
发送时间: 2024年12月31日(星期二) 晚上6:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Easonyesheng/A2PM-MESA] why i can&#39;t run the Benchmark Test?Can Bash run the test ? (Issue #9)














 
I have not tested this code on Windows.
 But according to the error info, , I think you can try to modify the shell script to make the python command in a single line? Not very sure.
 By the way, before running the script, you need to modify the data path in dataloader's  file.
 In your case, the  and  in  need to be fixed to your path of scannet data and SAM segmentation results.LexerNoViableAltException: dataset.image_name1=2520yamlroot_pathsem_folder/conf/dataset/scannet_sam.yaml

**Comment by Easonyesheng** [comment]
😄 
It looks like a `bash` problem.
I suggest you to directly run `python test_a2pm.py xxx a lot of text xxx` to rule out the code bug first.

**Comment by MY-QY** [comment]
thanks for your suggestion,i will try to solve it&nbsp;


FREE.ICE
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eason ***@***.***&gt;; 
发送时间: 2024年12月31日(星期二) 晚上7:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Easonyesheng/A2PM-MESA] why i can&#39;t run the Benchmark Test?Can Bash run the test ? (Issue #9)














 
😄
 It looks like a bash problem.
 I suggest you to directly run python test_a2pm.py xxx a lot of text xxx to rule out the code bug first.

**Comment by MY-QY** [comment]
[MESA.md](https://github.com/user-attachments/files/18282869/MESA.md)

I have run the project on Windows11 successfully.The settings are in the file.But maybe miss some values of result,anyone could fix it?

**Comment by MY-QY** [comment]
I have run the project on Windows11 successfully.The settings are in the file.But maybe miss some values of result, could&nbsp; you&nbsp; fix it?
If you are busy,forget it,
thanks for your answer again!!!






FREE.ICE
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Easonyesheng/A2PM-MESA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月31日(星期二) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Easonyesheng/A2PM-MESA] why i can't run the Benchmark Test?Can Bash run the test ? (Issue #9)





 
😄
 It looks like a bash problem.
 I suggest you to directly run python test_a2pm.py xxx a lot of text xxx to rule out the code bug first.

**Comment by Easonyesheng** [comment]
Appreciate it~ 
This operation manual has been put in [here](https://github.com/Easonyesheng/A2PM-MESA/blob/main/assets/run_MESA_on_win11.md) and mentioned in README.
